language: python
services:
  - docker

before_install: cd postprocessing-analysis
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.post-process:latest .
  - docker push $DOCKER_USER_NAME/captivate.post-process:latest

branches:
  only:
    - deploy/post-process