language: scala

before_install: cd api-gateway
script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt test

after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.api-gateway:latest .
  - docker push $DOCKER_USER_NAME/captivate.api-gateway:latest

branches:
  only:
    - deploy/api-gateway