language: python
services:
  - docker

before_install: cd model-execution
script:
  - echo "TODO - add unit test and integration tests"
after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.model-execution:latest .
  - docker push $DOCKER_USER_NAME/captivate.model-execution:latest

branches:
  only:
    - deploy/model-execution