language: java

before_install: cd UserManagement
script: 
  - 

after-success:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USER_NAME/captivate.user-management:latest .
  - docker push $DOCKER_USER_NAME/captivate.user-management:latest

branches:
  only:
    - deploy/user-management